stages:
  - check
  - test
  - publish

.common:
  image: docker.pkg.github.com/clash-lang/stack-templates/focal-ghc-cabal-stack:2020-11-28
  timeout: 2 hours
  stage: test
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  tags:
    - local
  before_script:
    - tar -xf cache.tar.zstd -C / || true
  after_script:
    - tar -cf - $(ls -d /root/.cabal /root/.stack /nix || true) | zstd -T0 -3 > cache.tar.zstd
  cache:
    key: $CI_JOB_NAME
    paths:
      - cache.tar.zstd

# Use ./render and check for changes
render:
  extends: .common
  stage: check
  script:
    - .ci/render_and_check.sh

# Build and test with Cabal
cabal:
  extends: .common
  script:
    - .ci/test_projects_cabal.sh

# Build and test with Stack
stack:
  extends: .common
  script:
    - .ci/test_projects_stack.sh

# Build and test with Nix
nix:
  extends: .common
  image: docker.pkg.github.com/clash-lang/stack-templates/nixos-xz-git:2020-11-28
  script:
    - bash .ci/test_projects_nix.sh

# If all tests pass, publish to 'clash-lang/clash-starters'.
publish:
  image: docker.pkg.github.com/clash-lang/stack-templates/publish:2020-11-30
  stage: publish
  script:
    - apt-get update
    - apt-install -y git ssh zip gzip tar coreutils haskell-stack
    - .ci/publish.sh
  only:
    refs:
      - master
