resolver: lts-15.10

extra-deps:
- concurrent-supply-0.1.8
- ghc-typelits-extra-0.4
- clash-prelude-1.2.5
- clash-lib-1.2.5
- clash-ghc-1.2.5

flags:
  clash-prelude:
    # 'large-tuples' generates tuple instances for various classes up to the
    # GHC imposed maximum of 62 elements. This severely slows down compiling
    # Clash, and triggers Template Haskell bugs on Windows. Hence, we disable
    # it by default. This will be the default for Clash >=1.4.
    large-tuples: false
